services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres_data: /var/lib/postgresql/16/main
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Asia/Jakarta"
      TZ: "Asia/Jakarta"

      # ---------- POSTGRES CONFIG ----------
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n

      # ---------- WEBHOOK CONFIG ----------
      WEBHOOK_URL: ${WEBHOOK_URL}
      
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
  postgres_data: